// ============================================================================
// Family.swift
// FamilyHub
//
// PURPOSE:
//   Represents a family group — the root organizational unit of the app.
//   All tasks, events, habits, and notifications are scoped to a family.
//
// FIRESTORE COLLECTION: `families`
//   One document per family. Members reference this via `FamilyUser.familyId`.
//
// INVITE CODE:
//   A 6-character alphanumeric code (generated by FamilyManagementService)
//   that new users enter to join the family. Codes are case-sensitive and
//   NOT rotated after use — a compromised code can be worked around by the
//   admin re-creating the family (future improvement: support code rotation).
//
// ============================================================================

import Foundation
import FirebaseFirestore

/// The root organizational unit for FamilyHub.
///
/// All domain data (tasks, events, habits, notifications) is scoped to a family
/// via the `familyId` field on each child document.
struct Family: Identifiable, Codable {

    /// Firestore document ID.
    @DocumentID var id: String?

    /// Display name shown in the family header (e.g., "The Johnson Family").
    var name: String

    /// 6-character alphanumeric invite code. Used by new members to join.
    /// Generated by `FamilyManagementService.generateInviteCode()`.
    var inviteCode: String

    /// Firebase UID of the family creator (also the first admin).
    var createdBy: String

    var createdAt: Date

    /// Array of Firebase UIDs of all current family members.
    /// Updated atomically by `FieldValue.arrayUnion` (join) and `FieldValue.arrayRemove` (leave/delete).
    var memberIds: [String]

    /// HTTPS URL to the family's banner/background image in Firebase Storage.
    /// Nil if no banner has been set.
    var bannerURL: String?
}
